github action: test check run on commit name change

diff --git a/.cloudbuild/test-webhook-label.yaml b/.cloudbuild/test-webhook-label.yaml
--- a/.cloudbuild/test-webhook-label.yaml
+++ b/.cloudbuild/test-webhook-label.yaml
@@ -5,19 +5,32 @@ steps:
       - -c
       - |
         echo "HERE _BODY ${_BODY} and _BRANCH_NAME ${_BRANCH_NAME} and _LABEL_NAME ${_LABEL_NAME} and _CHECK_RUN_ID ${_CHECK_RUN_ID} and _ACCESS_TOKEN ${_ACCESS_TOKEN}"
+        # Run your gcloud command here
+        if gcloud [YOUR_COMMAND]; then
+          export GCLOUD_EXIT_CODE=0  # Success
+        else
+          export GCLOUD_EXIT_CODE=$?  # Failure
+        fi
 
   - name: 'gcr.io/cloud-builders/curl'
     entrypoint: bash
     args:
       - -c
       - |
+        if [ "$GCLOUD_EXIT_CODE" -eq 0 ]; then
+          CONCLUSION="success"
+        else
+          CONCLUSION="failure"
+        fi
+
+        # Now perform your curl command based on the conclusion
         curl -L \
           -X PATCH \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $_ACCESS_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/helaouislim/training_ci_cd/check-runs/$_CHECK_RUN_ID \
-          -d '{"name": "mighty_readme","started_at": "2018-05-04T01:14:52Z","status": "completed","conclusion": "success","completed_at": "2018-05-04T01:14:52Z","output": {"title": "Mighty Readme report","summary": "There are 0 failures, 2 warnings, and 1 notices.","text": "You may have some misspelled words on lines 2 and 4. You also may want to add a section in your README about how to install your app."}}'
+          -d '{"name": "mighty_readme","started_at": "2018-05-04T01:14:52Z","status": "completed","conclusion": "'"$CONCLUSION"'","completed_at": "2018-05-04T01:14:52Z","output": {"title": "Mighty Readme report","summary": "There are 0 failures, 2 warnings, and 1 notices.","text": "You may have some misspelled words on lines 2 and 4. You also may want to add a section in your README about how to install your app."}}'
 
 substitutions:
   _BODY: '$(body)'
